seed: 3

model:
  _yaml_: _model.yaml
  confidence_head:
    blocks_per_ckpt: null

train:
  _yaml_: _train/full.yaml
  name: stage-confidence-2

  data:
    max_length: 768
    max_seq_length: 1024
    batch_size: 2
    global_batch_size: 256

    data_root: /cache/wykim_lab/icl_shwan/atlasfold_data/
    train_datasets:
      - name: rcsb
        is_distillation: false
        weight: 1.000
        sampling_strategy: ["length", "cluster"]
        metadata: /cache/wykim_lab/icl_shwan/atlasfold_data/rcsb/manifest_confidence.msgpack
    val_dataset:
      name: cameo_val

  training:
    train_confidence_head: true
    train_pae_head: true

    optimizer:
      ema_update_params: ["confidence_head."]
