seed: 4

model:
  _yaml_: _model.yaml
  confidence_head:
    blocks_per_ckpt: null

train:
  _yaml_: _train_base.yaml
  name: stage4

  data:
    max_length: 256
    max_seq_length: 512
    batch_size: 8
    global_batch_size: 256

    data_root: /cache/wykim_lab/icl_shwan/atlasfold_data/
    train_datasets:
      - name: rcsb
        metadata_path: /cache/wykim_lab/icl_shwan/atlasfold_data/rcsb/manifest_confidence.msgpack
        is_distillation: false
        weight: 1.0
        sampling_strategy: ["length", "cluster"]
    val_dataset:
      name: cameo_val

  training:
    train_trunk: false
    train_diffusion_head: false
    train_confidence_head: true
    train_pae_head: true
    num_recycles: 3

  loss:
    weights:
      pae: 0.1

  load_opt_state: false
  init_from_ema: ["trunk", "diffusion_head"]

  optimizer:
    max_lr: 1e-3
    lr_decay_factor: 1.0
    ema_update_params: ["confidence_head."]

  validation:
    num_recycles: 3
    num_diffusion_samples: 5
