seed: 1

model:
  _yaml_: _model.yaml
  confidence_head:
    blocks_per_ckpt: null

train:
  _yaml_: _train_base.yaml
  name: stage-4

  data:
    max_length: 512
    max_seq_length: 1024
    batch_size: 4
    global_batch_size: 256

    data_root: /cache/wykim_lab/icl_shwan/atlasfold_data/
    train_datasets:
      - name: rcsb
        is_distillation: false
        weight: 1.000
        sampling_strategy: ["cluster", "length"]
        metadata_path: /cache/wykim_lab/icl_shwan/atlasfold_data/rcsb/manifest_confidence.msgpack
    val_dataset:
      name: cameo_val

  training:
    train_confidence_head: true
    train_pae_head: true

  optimizer:
    max_lr: 1e-3
    lr_decay_factor: 1.0
    ema_update_params: ["confidence_head."]

  validation:
    num_diffusion_samples: 5
