model:
  _yaml_: _model.yaml
  lm_path: ./weights/atlaslm_3b_base.pth
  trunk:
    blocks_per_ckpt: null
  template_module:
    blocks_per_ckpt: null

train:
  _yaml_: _train_base.yaml
  name: multimer-ipa-stage3-640

  load_opt_state: false

  optimizer:
    max_lr: 0.0005
    lr_decay_factor: 1.0
    warmup_steps: 0

  loss:
    weights:
      violation: 0.5

  data:
    max_length: 640
    max_seq_length: 1280
    max_templates: 2
    max_contiguous_chains: 6

    data_root: /cache/wykim_lab/icl_shwan/atlasfold_data/
    train_datasets:
      # RCSB complex: 50%
      - name: rcsb_multimer_assembly
        type: rcsb
        is_multimer: true
        is_distillation: false
        use_templates: true
        weight: 0.50
        template_prob: 0.4

      # AFDB Multimer: 10%
      - name: afdb_homodimer
        type: multimer_distillation
        is_multimer: true
        is_distillation: true
        use_templates: false
        weight: 0.08
      - name: afdb_heterodimer
        type: multimer_distillation
        is_multimer: true
        is_distillation: true
        use_templates: false
        weight: 0.02

      # AFDB Monomer: 40%
      - name: long_monomers
        type: monomer_distillation
        is_multimer: false
        is_distillation: true
        use_templates: false
        weight: 0.40

    val_dataset:
      name: rcsb_multimer_val
      type: rcsb
      use_templates: false
