from atlasfold.model import model

monomer_config = model.AtlasFoldConfig(
    name="atlasfold-3b-base",
    lm_name="SeonghwanSeo/atlaslm-3b-base",
    channel_s=768,
    channel_z=192,
    trunk=model.TrunkConfig(
        dropout_z=0.25,
        num_heads=12,
        num_blocks=48,
        num_pair_to_single_blocks=4,
        num_lm_blocks=4,
    ),
    diffusion_head=model.DiffusionHeadConfig(
        channel_a=768,
        channel_atom=96,
        channel_cond=384,
        num_heads=16,
        num_blocks=12,
        num_atom_heads=2,
        num_atom_blocks=3,
    ),
    distogram_head=model.DistogramHeadConfig(
        num_bins=64,
        min_dist=2.0,
        max_dist=22.0,
    ),
    confidence_head=model.ConfidenceHeadConfig(
        channel_a=384,
        num_heads=12,
        dropout_z=0.25,
        num_blocks=4,
        num_bins=39,
        min_dist=3.25,
        max_dist=50.75,
        max_pae_error=32.0,
        num_pae_bins=64,
        num_plddt_bins=50,
    ),
)
