seed: 4

model:
  _yaml_: model/atlasfold.yaml
  trunk:
    blocks_per_ckpt: 6
  diffusion_head:
    blocks_per_ckpt: null
  confidence_head:
    blocks_per_ckpt: null

train:
  _yaml_: train/full.yaml
  name: stage4

  data:
    max_length: 640
    max_seq_length: 1280
    batch_size: 1
    global_batch_size: 256

    train_datasets:
      - name: rcsb
        is_distillation: false
        weight: 0.245
        sampling_strategy: ['length', 'cluster']
      - name: disordered_pdb
        is_distillation: true
        weight: 0.005
        sampling_strategy: ['length', 'cluster']
      - name: long_monomers
        is_distillation: true
        weight: 0.740
        sampling_strategy: ['length', 'plddt']
      - name: short_monomers
        is_distillation: true
        weight: 0.010
        sampling_strategy: ['length', 'plddt']

  training:
    train_trunk: true
    train_diffusion_head: true
    train_confidence_head: true
    train_pae_head: false
    diffusion_batch_size: 24

  optimizer:
    peak_lr: 1e-3
    decay_start_step: 100000000 # No decay
