model:
  _yaml_: model/atlasfold.yaml

train:
  _yaml_: train/full.yaml
  name: stage1

  data:
    max_length: 256
    max_seq_length: 512
    batch_size: 2
    global_batch_size: 128

  training:
    train_trunk: true
    train_diffusion_head: true
    train_confidence_head: false
    train_pae_head: false
    diffusion_batch_size: 32

  loss:
    weights:
      smooth_lddt: 1.0
