seed: 1

model:
  _yaml_: model/atlasfold.yaml
  trunk:
    blocks_per_ckpt: null
  diffusion_head:
    blocks_per_ckpt: null

train:
  _yaml_: train/full.yaml
  name: stage1

  data:
    max_length: 256
    max_seq_length: 512
    batch_size: 2
    global_batch_size: 256

    train_datasets:
      - name: rcsb
        is_distillation: false
        weight: 0.120
        sampling_strategy: ["length", "cluster"]
      - name: disordered_pdb
        is_distillation: true
        weight: 0.005
        sampling_strategy: ["length", "cluster"]
      - name: long_monomers
        is_distillation: true
        weight: 0.865
        sampling_strategy: ["length", "plddt"]
      - name: short_monomers
        is_distillation: true
        weight: 0.010
        sampling_strategy: ["length", "plddt"]

  training:
    train_trunk: true
    train_diffusion_head: true
    diffusion_batch_size: 32

  loss:
    weights:
      smooth_lddt: 1.0
