model:
  _yaml_: model/atlasfold.yaml

train:
  _yaml_: train/stage0.yaml
  name: stage5

  data:
    max_length: 768
    max_seq_length: 1280
    batch_size: 1
    global_batch_size: 128

  training:
    train_trunk: false
    train_diffusion_head: false
    train_confidence_head: true
    train_pae_head: true

  loss:
    weights:
      pae: 1.0

  optimizer:
    base_lr: 5e-4
    decay_start_step: 100000000 # No decay
    ema_update_params: ['confidence_head.']
