seed: 5

model:
  _yaml_: model/atlasfold.yaml
  trunk:
    blocks_per_ckpt: null
  diffusion_head:
    blocks_per_ckpt: null
  confidence_head:
    blocks_per_ckpt: null

train:
  _yaml_: train/stage0.yaml
  name: stage5

  data:
    max_length: 768
    max_seq_length: 1024
    batch_size: 1
    global_batch_size: 256

  training:
    train_trunk: false
    train_diffusion_head: false
    train_confidence_head: true

  loss:
    weights:
      pae: 1.0

  optimizer:
    peak_lr: 1e-3
    decay_start_step: 100000000 # No decay
    ema_update_params: ['confidence_head.']
