model:
  _yaml_: _model.yaml
  lm_path: ./weights/atlaslm_3b_base.pth
  trunk:
    blocks_per_ckpt: null

train:
  _yaml_: _train_base.yaml
  name: stage1-256
  seed: 1

  data:
    max_length: 256
    max_seq_length: 512
    cropper:
      prob_contiguous: 1.0
      prob_multi_contiguous: 0.0

    data_root: /cache/wykim_lab/icl_shwan/atlasfold_data/
    train_datasets:
      - name: rcsb
        is_distillation: false
        weight: 0.25
        sampling_strategy: ["length", "cluster"]
      - name: long_monomers
        is_distillation: true
        weight: 0.73
        sampling_strategy: ["length"]
        residue_plddt_threshold: 50.0
      - name: short_monomers
        is_distillation: true
        weight: 0.02
        sampling_strategy: ["length"]
        residue_plddt_threshold: 50.0
    val_dataset:
      name: cameo_val
