_yaml_: base.yaml

training:
  # Training step hyperparameters
  train_trunk: false
  train_diffusion_head: false
  train_confidence_head: true
  train_pae_head: true

data:
  data_root: ???
  train_datasets:
    - name: rcsb
      weight: 0.145
      sampling_strategy: ['length', 'cluster']
    - name: disordered_pdb
      weight: 0.005
      sampling_strategy: ['length', 'cluster']
    - name: long_monomers
      weight: 0.79
      sampling_strategy: ['length', 'plddt']
    - name: short_monomers
      weight: 0.01
      sampling_strategy: ['length', 'plddt']

  val_dataset:
    name: cameo_val
